[build]
  # Build command for Astro
  command = "npm run build"
  
  # Directory to publish (Astro's default output)
  publish = "dist"
  
  # Node.js version
  [build.environment]
    NODE_VERSION = "18"

# Redirect rules for SPA-like behavior
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Handle client-side routing for Astro pages
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache API responses for a short time
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "public, max-age=300"

# Environment variables (these will be set in Netlify dashboard)
[build.environment]
  # These will be overridden by Netlify dashboard settings
  PUBLIC_SUPABASE_URL = ""
  PUBLIC_SUPABASE_ANON_KEY = ""

# Functions configuration (if you want to use Netlify Functions later)
[functions]
  directory = "netlify/functions"
